---
services:
  scripts:
    container_name: oci_usage_cost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_CREDENTIALS=${N8N_CREDENTIALS}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - HEALTHCHECKS_URL_OCI_USAGE_COST=${HEALTHCHECKS_URL_OCI_USAGE_COST}
      - THRESHOLD=5.0
    volumes:
      - "./configuartion/config:/scripts/config"
      - "./configuration/oci.pem:/scripts/oci.pem"
    network_mode: host
