---
services:
  scripts:
    container_name: oci_usage_cost
    # image: oci_usage_cost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_ACCESS_TOKEN=${NTFY_ACCESS_TOKEN}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - HEALTHCHECKS_URL_OCI_USAGE_COST=${HEALTHCHECKS_URL_OCI_USAGE_COST}
      - GOTIFY_HOST=${GOTIFY_HOST}
      - GOTIFY_TOKEN_ADHOC_SCRIPTS=${GOTIFY_TOKEN_ADHOC_SCRIPTS}
      - THRESHOLD=5
      - INTERVAL_MINS=60
    volumes:
      - './configuartion/config:/scripts/config'
      - './configuration/oci.pem:/scripts/oci.pem'
    network_mode: host
